name: Context with Environment

on: [push]

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print GitHub Context
        run: |
          echo "Current Repository: $MY_REPO"
          echo "Current Action: $MY_ACTION"
        env:
            MY_REPO: ${{github.repository}}
            MY_ACTION: ${{github.action}}
